#!/bin/bash

cat <<EOF >> ~/.profile
alias ll="ls -al --color"
alias k=kubectl
alias t=terraform
alias g=gcloud
EOF

alias ll="ls -al --color"
alias k=kubectl
alias t=terraform
alias g=gcloud

[ -f /usr/bin/gcloud ] && gcloud config set accessibility/screen_reader False
